### ISSUE TITLE
DB reload on new result

### ISSUE THREAD

**Issue by galwiner** [entropy-lab/entropy#102]
When a new experiment is saved to the same DB, it is not shown on the results browser until the server is re-run.

**Comment by galwiner** [comment]
@urig is this a hard fix?

**Comment by urig** [comment]
Thanks for the report. Shouldn't be hard to fix. Will update later today.

**Comment by urig** [comment]
@galwiner a page refresh (F5) now refreshes the contents of the experiments table from the DB. Will this do for now or shall I also add a table refresh to occur every X seconds?

**Comment by urig** [comment]
@galwiner nag

**Comment by urig** [comment]
@galwiner friendly nag :)

**Comment by galwiner** [comment]
if the page is refreshed automatically and there are selections/filters (ongoing user work), will everything be reset? 
if so that may be annoying and we would not want to refresh
how will it behave? like ynet 8 years ago where the page would refresh while you are reading an article?

**Comment by urig** [comment]
@galwiner The idea is that only the experiments table will be refreshed without impacting other parts of the page. Not a full page re-rendering.

**Comment by galwiner** [comment]
in that case, I think a periodic reload every 10-20 seconds could be good. 
what about a reload button? maybe that's better?

**Comment by urig** [comment]
a button imho is less desirable. I'll quickly set-up an automated refresh and demo to you.

**Comment by urig** [comment]
@galwiner fix is on main. please close this PR. Thanks.
