### ISSUE TITLE
simplify the imports when using entropy

### ISSUE THREAD

**Issue by galwiner** [entropy-lab/entropy#110]
Looking at some of our tests, e.g. `test_example.py` it's clear users need to import many things from deep inside the `entropylab` package. 
This is not a good user experience. 
we need to have a simple single line import that covers 85% of the use cases in writing simple graphs

**Comment by qguyk** [comment]
it's considered best practice in python to import by name so you won't import unnecessary stuff, so in our test we force it.

actually we can replace the imports there with a single line
`from entropylab import *`
and it will work.
do you have more examples about imports, we can check it's all covered

**Comment by galwiner** [comment]
I understand and agree with your point about best practices, but I think we are making it too hard for the user to work. 
I think we should have a recommended import mode, e.g. `import entropylab as el` 
then have as many common methods on top-level, or at least make sure the structure makes sense. 
for example: `from entropylab.instruments.lab_topology import ExperimentResources, LabResources` 
forces the user to go two levels down, and go via something that has a scary name ("topology") to access something they will always need
