### ISSUE TITLE
Propagate EntropyError messages to user 

### ISSUE THREAD

**Issue by galwiner** [entropy-lab/entropy#115]
When users use different features of the plotting dashboards there can be errors. 
for example, the automatic plotting may fail, resulting in `EntropyError`

This is currently a silent fail. the user does not see a plot and nothing else happens (which is preferred behaviour to a crash of course)

It could be a nice enhancement to allow a user to see that an error has occurred in a status line of some sort.

**Comment by galwiner** [comment]
@urig  FYI

**Comment by urig** [comment]
Hi @galwiner. The improvements you've described have been implemented in other issues. Would you like to close this issue?

**Comment by galwiner** [comment]
Yes, I'll close it. Thanks
