### ISSUE TITLE
SqlAlchemyDB: get_results_from_node() returns all nodes and not just based on a label

### ISSUE THREAD

**Issue by galwiner** [entropy-lab/entropy#123]
When `SqlAlchemyDB.get_results_from_node('label")` is used all results in the db are returned and not just those specified by the label. 

Steps to reproduce: 

Checkout `complex-db` branch
run `test_fetch_2d_array` test

**Comment by urig** [comment]
@galwiner I've reproduced the behavior in the test but I don't quite understand what the expected behavior is. Perhaps you, @qguyk and I can sync online for this?

**Comment by urig** [comment]
Following our online discussion today it's realized that this is a bug in `get_nodes_id_by_label()`. It returns a list of `Node` `id` properties but the unique identifier for `Node`s actually the combination of its `id` and `experiment_id` together.

A quick fix would be to make `get_results_from_node()` return tuples of node `id` and `experiment_id` and re-integrate into any locations calling it.

A more thorough solution is proposed in discussion https://github.com/entropy-lab/entropy/discussions/145

**Comment by galwiner** [comment]
Hey @urig, did you make progress on this?

**Comment by urig** [comment]
Hi Gal. No I haven't. Would love to go for the more thorough solution seeing as we're pre-1.0. Should I?

**Comment by urig** [comment]
Hi @galwiner. https://github.com/entropy-lab/entropy/pull/203 resolves this issue and has been merged to `main`. Can we close it?
