### ISSUE TITLE
calling entropy serve with waitress WSGI does not print a message with ip and port of the running dashboard

### ISSUE THREAD

**Issue by galwiner** [entropy-lab/entropy#134]
As a user I expect the `entropy serve` message to print a message with information on the running server (telling me it is alive) and where to find the dashboard page (IP + port number)

**Comment by urig** [comment]
Might have been resolved by https://github.com/entropy-lab/entropy/pull/213

Resolution might be obscured by our introduction of `hupper ` to manage the `waitress` process.
