### ISSUE TITLE
enable debug even if --debug not specified

### ISSUE THREAD

**Issue by galwiner** [entropy-lab/entropy#157]
The dash debug tool is useful even if not explicitly needed. 
let's add it by default

**Comment by galwiner** [comment]
@urig

**Comment by nikolaqm** [comment]
Maybe it would be useful to add automatic browser opening like we did for config GUI? 

https://github.com/qua-platform/py-qua-tools/blob/main/qualang_tools/config/gui.py#L105

It prints location, and also opens that location. It is bit less then full debug (that would log every single GET). What do you think @galwiner  ?

**Comment by galwiner** [comment]
A print message is highly desireable. Auto-launch browser too. 
There was an issue with getting it working. @urig can explain.

**Comment by urig** [comment]
@nikolaqm thanks. launching the browser is s a neat idea. I'll add it to the dashboard.
