### ISSUE TITLE
Bug in function build_plot_tab_from_plot

### ISSUE THREAD

**Issue by ilanmitnikov** [entropy-lab/entropy#187]
Had to change the parameter 'color' to 'line_color' inside generator.plot_plotly otherwise the plot would not render

**Comment by galwiner** [comment]
@urig

**Comment by urig** [comment]
@ilanmitnikov thank you for reporting this. Can you let me know how I can reproduce this behavior? Maybe share your plot/data here or at uri.goldstein at gmail dot com? 🙏🏻

**Comment by urig** [comment]
@galwiner as I've not been able to reproduce and as we're in progress of replacing the plotting API I suggest we close this issue.
