### ISSUE TITLE
Let user create their own figure object in plot generator

### ISSUE THREAD

**Issue by ilanmitnikov** [entropy-lab/entropy#188]
Instead of passing a figure object to generator.plot_plotly let user create their own. It provides more flexibility and convenience.
For example, with that one can use plotly.express which is a nicer interface.
 
I'd make the following changes, obviously care need with the different paramters such as color etc.
```python
   def build_plot_tab_from_plot(
        plot_figures, plot: PlotRecord, color: str
    ) -> (dbc.Tab, Dict):
        plot_key = f"{plot.experiment_id}/{plot.id}"
        plot_name = f"Plot {plot_key}"
        # plot_figure = go.Figure()
        plot_figure = plot.generator.plot_plotly(
            # plot_figure,
            plot.plot_data,
            name=plot_name,
            # line_color=color,
            # showlegend=False,
        )
        plot_figure.update_layout(dark_plot_layout)
        plot_figures[plot_key] = dict(figure=plot_figure, color=color)
        return build_plot_tab(plot_figure, plot_name, plot_key), plot_figures
```

**Comment by urig** [comment]
Answers:
1. We will no longer color figures automatically in the "plots tab". The question remains - do we need to intervene in trace colors shown in the Aggregate tab?
2. We will auto-migrate from the figures table to the figures table at a later release, when we deprecated the older API.
3. Pending deprecation now, full deprecation in a future release soon.

**Comment by urig** [comment]
1. Remove FigureSpec in favor of passing in go.Figure directly.
2. Which figures to automatically color? If at all?

**Comment by urig** [comment]
Hi @galwiner. Now that the new plotting API - based on `go.Figure` objects - is merged to `main` I think we can close this issue. Would you agree?

**Comment by urig** [comment]
Hi @ilanmitnikov. We have a new plotting API on `main` that lets users bring in any `go.Figure` object that they want and save it along with experiment results, later to be reviewed in the Entropy Dashboard. We would love to get your feedback on it! Full details can be found in PR https://github.com/entropy-lab/entropy/pull/195.
