### ISSUE TITLE
paramstore methods not shown by __dir__

### ISSUE THREAD

**Issue by galwiner** [entropy-lab/entropy#208]
paramstore methods, such as `commit`, `to_dict` or `list_values` don't appear on an IDE autocomplete
this is probably because of the `__dir__ `method of Munch

**Comment by urig** [comment]
I tried reproducing in PyCharm and auto-complete is showing these methods:

![image](https://user-images.githubusercontent.com/350687/163351184-44b1d1ca-76b1-43ad-92b6-affc59ae5e1e.png)

How can I reproduce this?
