### ISSUE TITLE
paramstore uses GMT and not local time when time stamping commits

### ISSUE THREAD

**Issue by galwiner** [entropy-lab/entropy#221]
when calling commit, the "ns" time stamp for the commit uses GMT and not the local timezone
also I wonder if "ns" is not a misleading name and should be changed to "time-stamp"

**Comment by urig** [comment]
The ns timestamp is and should be stored in the ParamStore in UTC because...
As we've discussed I will modify the retrieval of `ns` timestamps to translate the UTC value to the user's local timezone.
Additionally `ns'`shall be renamed 'timestamp' in commit `Metadata`.
