### ISSUE TITLE
experiment ID falls out of sync when working from two python IDEs

### ISSUE THREAD

**Issue by liorella-qm** [entropy-lab/entropy#223]
I am running code both from jupyter lab and from pycharm.

It seems that the code from jupyter lab tries to overwrite already existing experiment IDs because it's not synced to what are the correct experiment IDs to work on.

Please see a video describing this:
https://www.loom.com/share/5200d50ea6374fd59a1ff3d456e18aae

**Comment by urig** [comment]
The `InProcessParamStore` currently in use in Entropy does not support multi-threaded and multi-process use.

We can consider augmenting it to support both scenarios by implementing the ["lock file" pattern](https://en.wikipedia.org/wiki/File_locking#Lock_files). The [`filelock`](https://py-filelock.readthedocs.io/en/latest/index.html) library is a good candidate for getting this done.

⚠ The above solution will possibly have an impact on `ParamStore` write performance as the pattern dictates that only a single consumer (thread/process) can write to the file at any given time.

**Comment by liorella-qm** [comment]
This is how we work now in practive, and we must have it if we want to work with entropy flame.

> ⚠ The above solution will possibly have an impact on ParamStore write performance as the pattern dictates that only a single consumer (thread/process) can write to the file at any given time.

not sure I understand this. Currently we don't support multi-process, so the performance impact is relative to what?

**Comment by galwiner** [comment]
@urig , we discussed and the suggested fix sounds like a step in the right direction. 
If we end up with an unacceptable performance hit, then we will have to discuss it again but for now, let's go on with it. 

thanks!
