### ISSUE TITLE
[BUG] node dependency created with keyword argument `must_run_after` fails to give correct ancestors

### ISSUE THREAD

**Issue by eunjongkim** [entropy-lab/entropy#248]
**Describe the bug**
The ancestors() method on the node with dependencies created with `must_run_after` only outputs the current node.

**To Reproduce**
Simple code to reproduce this:
```
from entropylab import PyNode, Graph

def node_operation():
    return {'res': 1}

node1 = PyNode(label='a', program=node_operation)
node2 = PyNode(label='b', program=node_operation,
               must_run_after={node1})
node3 = PyNode(label='c', program=node_operation,
               must_run_after={node2})

experiment = Graph(resources=None, graph={node1, node2, node3}, story='run')
handle = experiment.run()
```
This gives a graph that looks like this:
![image](https://user-images.githubusercontent.com/8111538/171091627-40e56fa9-54f2-4aa1-a0ec-73a9e6a433ef.png)

Therefore `node3.ancestors()` is expected to return a set consisting of `node1`, `node2`, and `node3`. However, I find that this only returns the current node (`node3`).

**Comment by eunjongkim** [comment]
I created a pull request #255 to fix this bug. Please take a look.

**Comment by qguyk** [comment]
Thank you @eunjongkim for identifying the issue and fixing it :) 
the pull request is not merged, so i'm closing the issue
please reopen it if needed.
#fixed
