### ISSUE TITLE
HDF5 backend for Entropy

### ISSUE THREAD

**Issue by galwiner** [entropy-lab/entropy#25]
Entropy saving should support HDF5 as a backend. 

We need to make sure QPU-DB is on equal footing here.

**Comment by liorella-qm** [comment]
@galwiner qpu-db can't (+ shouldn't) be on equal footing here becuase it has a different representation and purposes. It's a pickling + version tracking based DB. Currently it uses ZODB, but the plan it to make it based on git.

**Comment by galwiner** [comment]
@talshani ,@qguyk  we need to discuss if the QPU-DB is a resource that should be save on the "persistence backend" or not.
